backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - file: "index.html"
        label: "Página Principal"
        name: "home"
        fields:
          - { label: "Contenido HTML", name: "body", widget: "text" }
